### ISSUE TITLE
[Bug]: remove-itglueflexibleasset not working for bulk destroys - probably user error?

### ISSUE THREAD

**Issue by AHelsby** [Celerium/ITGlue-PowerShellWrapper#6]
### What happened?

Just loaded your version instead of the original wrapper to work with bulk deleting flexible assets.
However when I pass a jsonstring (or object)  to remove-itglueflexibleasset, I get 500 error from ITGlue.

I've taken some sample  id's and formatted the text (which may be the incorrect way to go but it works for an invoke-webrequest command)  as follows.

```powershell
$test=get-itglueflexibleasset -FilterFlexibleAssetTypeID 79975 -FilterOrganizationID 123456789
$ids = $test.data.id
$data = @()
foreach ($id in $ids) {
     $data += [PSCustomObject]@{
         type  = "flexible-assets"
         attributes = @{
             id = $id
         }
     }
 }

$jsonObject = [PSCustomObject]@{
     data = $data
 }
# Convert to JSON string
$jsonString = $jsonObject | ConvertTo-Json -Depth 3
```
The Json string looks like the following which matches ITGlue's documented requirement

```
$jsonString
{
  "data": [
    {
      "type": "flexible-assets",
      "attributes": {
        "id": "90706543"
      }
    },
    {
      "type": "flexible-assets",
      "attributes": {
        "id": "90706547"
      }
    }
  ]
}

``` 
I'm kind of curious that the bulk_destroy option does not show up in the autocomplete parameter set for remove-itglueflexibleasset command 

```
Remove-ITGlueFlexibleAsset -data $jsonstring -WhatIf
WhatIf               Debug                InformationAction    WarningVariable      OutBuffer
Confirm              ErrorAction          ProgressAction       InformationVariable  PipelineVariable
Verbose              WarningAction        ErrorVariable        OutVariable

```

The errors if I run with the remove-itglueflexibleasset  vs the invoke-webrequest line below.

```
13:28:49: Scripts> Remove-ITGlueFlexibleAsset -data $jsonstring

Confirm
Are you sure you want to perform this action?
Performing the operation "Remove-ITGlueFlexibleAsset" on target "/flexible_assets".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): A
WARNING: The [ Invoke_ITGlueRequest_Parameters, Invoke_ITGlueRequest_ParametersQuery, & CmdletName_Parameters ] variables can provide extra details
Invoke-ITGlueRequest: C:\Users\me\AppData\Local\powershell\Modules\itglueapi\Public\FlexibleAssets\Remove-ITGlueFlexibleAsset.ps1:65
Line |
  65 |  …      return Invoke-ITGlueRequest -Method DELETE -ResourceURI $Resourc …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Response status code does not indicate success: 500 (Internal Server Error).

invoke-webrequest  -uri "https://api.itglue.com/flexible_assets/" -Headers $itgheaders -Method DELETE -Body $jsonstring

StatusCode        : 200
StatusDescription : OK
Content           : {123, 34, 100, 97…}
RawContent        : HTTP/1.1 200 OK
                    Date: Tue, 12 Nov 2024 18:39:34 GMT
                    Connection: keep-alive
                    Set-Cookie: <snip>
Headers           : {[Date, System.String[]], [Connection, System.String[]], [Set-Cookie, System.String[]], [Server, System.String[]]…}
RawContentLength  : 978
RelationLink      : {}

```
I've probably missed something, but am I missing something in how the data should be passed in the parameter, is there a reason why the bulk_destroy is not an option?

### Expected behavior?

Would expect the two flexible assets to be deleted.

### Possible Solution?

for now use invoke-webrequest

### PowerShell Version

7.4.x - (PowerShell Core)

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```PowerShell
Line |
  65 |  …      return Invoke-ITGlueRequest -Method DELETE -ResourceURI $Resourc …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Response status code does not indicate success: 500 (Internal Server Error)
```

### Help Commands

```PowerShell
get-module itglue -listavailable
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     3.0.0                 ITGlueAPI                           Desk      {Remove-ITGlueAPIKey, Get-ITGlueOrganizationType, Set-ITGlueContact, Remove-ITGlueLocation…} )
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Celerium** [comment]
Hi @AHelsby,

1. JSON
After you run the command you can leverage some of the help variables that get set to troubleshoot. What do you see if you rerun it and expand out the $Invoke_ITGlueRequest_Parameters variable, mainly the "body" attribute?

In your case, these three global variables should be present after you run Remove-ITGlueFlexibleAsset
- $Invoke_ITGlueRequest_Parameters
- $Invoke_ITGlueRequest_ParametersQuery
- $Remove_ITGlueFlexibleAsset_Parameters

If I could guess, I think the JSON might be getting double-encased as the "Invoke-ITGlueRequest" takes the inputted data and converts it to JSON.
![image](https://github.com/user-attachments/assets/8395ca72-a1a7-4512-8baf-066f64e8fb41)

If that is the case it might just be bad wording with the documentation. I have always given data a hashtable to psobject that is JSON formatted. This data is then sent to the "Invoke-ITGlueRequest" function to handle.

    .PARAMETER Data
        JSON object or array depending on bulk changes or not

2.  Bulk_Destory parameter
This is not a parameter because if an "ID" is defined then only that defined flexible asset is deleted. When the data parameter is used this allows 1 or more defined flexible assets to be deleted in bulk

https://api.itglue.com/developer/#flexible-assets-destroy
https://api.itglue.com/developer/#flexible-assets-bulk-destroy

![image](https://github.com/user-attachments/assets/f14ee72b-a0cc-4507-bf3c-be9a7b689dbd)


Hope this helps

**Comment by Celerium** [comment]
On mobile right now, but yup you are double encasing the data section. For the json your inputting you don't need the data section because the invoke-itgluerequest function handles the encasing.

And yes for bulk destroy, you pass a single json object (without the data section) with the ids you want to destroy.
